lk_velocity_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ['lf_wheel_joint', 'lb_wheel_joint']
  right_wheel: ['rf_wheel_joint', 'rb_wheel_joint']
  publish_rate: 50
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
  cmd_vel_timeout: 0.25

  k_l: 0.5
  k_r: 0.5

  # Odometry fused with IMU is published by robot_localization, so
  # no need to publish a TF based on encoders alone.
  enable_odom_tf: false

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 20.0   # m/s
      has_acceleration_limits: true
      max_acceleration       : 20.0   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 12.0   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 25.0   # rad/s^2


lk_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

# lk_dump_controller:
  # type: "velocity_controllers/JointPositionController"
  # joint: "dump"
  # pid: {p: 1.0, i: 0.08, d: 0.0}

# lk_ladder_controller:
  # type: "velocity_controllers/JointPositionController"
  # joint: "ladder"
  # pid: {p: 1.0, i: 0.04, d: 0.0}

# lk_spin_controller:
  # type: "effort_controllers/JointEffortController"
  # joint: "spin"

# lk_flap_controller:
  # type: "position_controllers/JointPositionController"
  # joint: "flap"
