# TODO: convert into a tag bundle
standalone_tags: [
    {id: 0, size: 0.160, name: "tag1"},
    {id: 6, size: 0.160, name: "tag2"},
    {id: 8, size: 0.160, name: "tag3"},
    {id: 10, size: 0.160, name: "tag4"}
  ]
